// see 1 record per row
RawLogs
| extend records =  parse_json(records)
| extend item = (records)
| mv-expand item
| extend customDimensionsObject =  parse_json(item.Properties)
| extend test_run_id = tostring(customDimensionsObject.test_run_id)
| extend llm_version = customDimensionsObject.llm_version
| extend llm_model = customDimensionsObject.llm_model
| extend temperature = customDimensionsObject.temperature
| extend query_id = toint(customDimensionsObject.query_id)
| extend prompt_name = tostring(customDimensionsObject.prompt_name)
| extend coherence = toreal(customDimensionsObject.coherence)
| extend groundedness = toreal(customDimensionsObject.groundedness)
| extend relevance = toreal(customDimensionsObject.relevance)


// graph 
RawLogs
| extend records =  parse_json(records)
| extend item = (records)
| mv-expand item
| extend customDimensionsObject =  parse_json(item.Properties)
| extend test_run_id = tostring(customDimensionsObject.test_run_id)
| extend llm_version = customDimensionsObject.llm_version
| extend llm_model = customDimensionsObject.llm_model
| extend temperature = customDimensionsObject.temperature
| extend query_id = toint(customDimensionsObject.query_id)
| extend prompt_name = tostring(customDimensionsObject.prompt_name)
| extend coherence = toreal(customDimensionsObject.coherence)
| extend groundedness = toreal(customDimensionsObject.groundedness)
| extend relevance = toreal(customDimensionsObject.relevance)
| summarize 
    AvgCoherence = avg(coherence),
    AvgGroundedness = avg(groundedness), 
    AvgRelevance = avg(relevance)
by 
    test_run_id,
    prompt_name


// graph ADX
RawLogs
| extend records =  parse_json(records)
| extend item = (records)
| mv-expand item
| extend customDimensionsObject =  parse_json(item.Properties)
| extend test_run_id = tostring(customDimensionsObject.test_run_id)
| extend llm_version = customDimensionsObject.llm_version
| extend llm_model = customDimensionsObject.llm_model
| extend temperature = customDimensionsObject.temperature
| extend query_id = toint(customDimensionsObject.query_id)
| extend prompt_name = tostring(customDimensionsObject.prompt_name)
| extend coherence = toreal(customDimensionsObject.coherence)
| extend groundedness = toreal(customDimensionsObject.groundedness)
| extend relevance = toreal(customDimensionsObject.relevance)
| summarize 
    AvgCoherence = avg(coherence),
    AvgGroundedness = avg(groundedness), 
    AvgRelevance = avg(relevance)
by 
    test_run_id,
    prompt_name
|sort by prompt_name
| render columnchart  




